### PR TITLE
fix: icon names QQ, VK

### PR DESCRIPTION
**Pull request by goldfndr**

### CODE REVIEW

**Comment by goldfndr** [comment]
Something I'm curious about: how did you decide what order to put the icons? I'd've thought you'd've put them in the order they appear in the file (sort by offset).

**Comment by goldfndr** [comment]
The Tencent QQ offsets are probably incorrect.

**Comment by berryelectronics** [comment]
Hey, sorry for the late response, i've been busy lately but will try to respond to you this week :)

**Comment by berryelectronics** [comment]
I ordered the icons by their appearance in the "Mi Band Master" App, mostly because i used the icon list on it as a first place to search for all the icons. Not the best measure but the best i had at the time

**Comment by goldfndr** [comment]
[I see.](http://pic.downcc.com/upload/2018-2/201822021320763760.jpg)

[This list shows more](http://fii.cz/gzehgts) but, given that the images are inverted (and [an older copy of the image also has the list icon](https://imgur.com/IdhALiT)) I don't know how authentic they are.

**Comment by berryelectronics** [comment]
Hey, gonna merge it and check the tencent qq offsets.

**Pull request merged**
